---
title: "D25_Analysis_manuscript"
author: "GKT"
date: "2025-06-23"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(DESeq2)
library(fgsea)
library(msigdbr)
```

```{r}
maxMinFilter <- function(object, intgroup = "condition", comp = c("ctrl","trmt"), thresh = 0)
{
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  
  group <- if (length(intgroup) > 1) {
    interaction(lapply(intgroup, function(factorname) colData(ddsMoTime20034)[[factorname]]), drop = TRUE)
  }
  else {
    colData(object)[[intgroup]]
  }
  if (!all(comp %in% levels(group))) {
    stop("the argument 'comp' should specify levels of intgroup")
  }
  if_else(rowMaxs(sapply(comp, function(lvl) rowMins(counts(object, normalize = TRUE)[,group == lvl]))) > thresh,rowMeans2(counts(object, normalized = TRUE)),0)
}

as.annot.data.frame <- function(object, var = "gene_id", subset = "all", relabel = "", newlabel = "", select = c("gene","baseMean","log2FoldChange","pvalue","padj"))
{
  df <- rownames_to_column(as.data.frame(object), var = var) %>% rename_at(vars(2:7), function(x) paste0(names(object)[1:6], " (", object@elementMetadata$description[1:6], ")"))
  if(subset != "all") {
    subset
    names(df)[2:7]
#    df <- df %>% rename_at(vars(2:7), function(x) gsub(": ", paste0(": ",subset," "), gsub("all",subset, names(df)[2:7])))
    df <- df %>% rename_at(vars(2:7), function(x) gsub("all", subset, names(df)[2:7]))
  }
  if(relabel != "" & newlabel != "") {
    df <- df %>% rename_at(vars(2:7), function(x) gsub(relabel, newlabel, names(df)[2:7], fixed = TRUE))
    relabel_nous <- gsub("_"," ",relabel)
    df <- df %>% rename_at(vars(2:7), function(x) gsub(relabel_nous, newlabel, names(df)[2:7], fixed = TRUE))
    df <- df %>% rename_at(vars(2:7), function(x) gsub("p-values", paste0("p-values: ",newlabel), names(df)[2:7], fixed = TRUE))
  }
  if(length(select) > 1) {
    df <- df %>% select(contains(select))
  }
  df
}


```

```{r}
analysis = list()

analysis$sampleTable <- read.csv("../outputs/sample_table_p24027_Tomas_Analysis.csv")

raw_counts <- read.csv("../outputs/raw_count_p24027_Tomas_Analysis.csv") %>%
  column_to_rownames(var = "gene_id")

analysis$dds <- DESeqDataSetFromMatrix(raw_counts,
                                       analysis$sampleTable,
                                       design = as.formula( ~ Venetoclax))

analysis$dds <- DESeq(analysis$dds, parallel = TRUE)

```

```{r}
## Compare Any Venetoclax treatment (VA) to Only ART(A):(VA/A)
resVenetoclax <- results(analysis$dds,
                         name = "Venetoclax_Venetoclax_vs_None",
                         alpha = 0.05,
                         filter = maxMinFilter(analysis$dds,
                                               intgroup = "Venetoclax",
                                               comp = c("None","Venetoclax"))
                         )

```

```{r}

analysis$ddsGroup <- DESeqDataSetFromMatrix(counts(analysis$dds),
                                            select(as.data.frame(colData(analysis$dds)),
                                                   -c(sizeFactor,replaceable)),
                                            design = ~ Group)
analysis$ddsGroup <- DESeq(analysis$ddsGroup, parallel = TRUE)

```

```{r}
## Compare ART anti-CD8 Venetoclax (AVC) to ART Venetoclax (AV):(AVC/AV)
resAVCvsAV <- results(analysis$ddsGroup,
                contrast = c("Group","ARTposVenetoclaxposantiposCD8","ARTposVenetoclax"),
                alpha = 0.05,
                filter = maxMinFilter(analysis$ddsGroup,
                                      intgroup = "Group",
                                      comp = c("ARTposVenetoclaxposantiposCD8",
                                               "ARTposVenetoclax")))

```


```{r}
as.annot.data.frame(resVenetoclax,
                    subset = "All",
                    relabel = "Venetoclax Venetoclax vs None",
                    newlabel = "Venetoclax vs ART") %>%
  left_join(as.annot.data.frame(resAVCvsAV,
                                subset = "All",
                                relabel = "Group ARTposVenetoclaxposantiposCD8 vs ARTposVenetoclax",
                                newlabel = "anti-CD8 Venetoclax vs Venetoclax")) %>%
  openxlsx::write.xlsx(file = "../outputs/Merged_DESeq2_results_p24027_Tomas-manuscript.xlsx")
```

```{r}
gmt.file <- list()

catlist <- c("H")
subcatlist <- c("CP:","GO:BP")

gmt.file <- sapply(filter(msigdbr_collections(),
              gs_cat %in% catlist |
                gs_subcat %in% (sapply(subcatlist,
                                       function(x){str_subset(msigdbr_collections() %>%
                                                                pull(gs_subcat),x)},
                                       USE.NAMES = TRUE) %>%
                                  unlist())) %>%
         split(1:7),
       function(x){msigdbr(species = "Homo sapiens",
                           category = x[1,]$gs_cat,
                           subcategory = x[1,]$gs_subcat) %>%
           dplyr::select(gene_symbol, gs_name)},simplify = FALSE) %>%
  bind_rows() %>%
  unstack()

bioplanet.pathways <- read_csv("../config/pathway.csv")
bioplanet.pathway.category <- read_csv("../config/pathway-category.csv")

bioplanet.gmt.file <- sapply(unique(bioplanet.pathways$PATHWAY_NAME),
                             function(pathway) {
                               filter(bioplanet.pathways, PATHWAY_NAME==pathway) %>%
                                 pull(GENE_SYMBOL)
                             },simplify = FALSE)

extended.gmt.file <- c(set_names(bioplanet.gmt.file,str_c("bioplanet_",names(bioplanet.gmt.file))),gmt.file)


```

```{r}
VAvsA.D25 = fgsea(extended.gmt.file,
                           as.data.frame(resVenetoclax) %>%
                             filter(!is.na(padj)) %>%
                             select(stat) %>%
                             rownames_to_column() %>%
                             pull(stat,name=rowname)) %>%
    mutate(source = str_extract(pathway,"[^_]*"),.before = pathway) %>%
    arrange(pval)

openxlsx::write.xlsx(VAvsA.D25,"../outputs/Day25_VAvsA_GSEA_MSigSB-bioplanet_results-manuscript.xlsx")


```

