---
title: "D294_Analysis_manuscript"
author: "GKT"
date: "2025-06-23"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(DESeq2)
library(fgsea)
library(msigdbr)
```

```{r}
maxMinFilter <- function(object, intgroup = "condition", comp = c("ctrl","trmt"), thresh = 0)
{
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  
  group <- if (length(intgroup) > 1) {
    interaction(lapply(intgroup, function(factorname) colData(ddsMoTime20034)[[factorname]]), drop = TRUE)
  }
  else {
    colData(object)[[intgroup]]
  }
  if (!all(comp %in% levels(group))) {
    stop("the argument 'comp' should specify levels of intgroup")
  }
  if_else(rowMaxs(sapply(comp, function(lvl) rowMins(counts(object, normalize = TRUE)[,group == lvl]))) > thresh,rowMeans2(counts(object, normalized = TRUE)),0)
}

as.annot.data.frame <- function(object, var = "gene_id", subset = "all", relabel = "", newlabel = "", select = c("gene","baseMean","log2FoldChange","pvalue","padj"))
{
  df <- rownames_to_column(as.data.frame(object), var = var) %>% rename_at(vars(2:7), function(x) paste0(names(object)[1:6], " (", object@elementMetadata$description[1:6], ")"))
  if(subset != "all") {
    subset
    names(df)[2:7]
#    df <- df %>% rename_at(vars(2:7), function(x) gsub(": ", paste0(": ",subset," "), gsub("all",subset, names(df)[2:7])))
    df <- df %>% rename_at(vars(2:7), function(x) gsub("all", subset, names(df)[2:7]))
  }
  if(relabel != "" & newlabel != "") {
    df <- df %>% rename_at(vars(2:7), function(x) gsub(relabel, newlabel, names(df)[2:7], fixed = TRUE))
    relabel_nous <- gsub("_"," ",relabel)
    df <- df %>% rename_at(vars(2:7), function(x) gsub(relabel_nous, newlabel, names(df)[2:7], fixed = TRUE))
    df <- df %>% rename_at(vars(2:7), function(x) gsub("p-values", paste0("p-values: ",newlabel), names(df)[2:7], fixed = TRUE))
  }
  if(length(select) > 1) {
    df <- df %>% select(contains(select))
  }
  df
}


```

```{r}
analysis2 = list()

analysis2$sampleTable <- read.csv("../outputs/sample_table_p24155_Tomas_Processing.csv")

raw_counts2 <- read.csv("../outputs/raw_count_p24155_Tomas_Processing.csv") %>%
  column_to_rownames(var = "gene_id")

analysis2$dds <- DESeqDataSetFromMatrix(raw_counts2,
                                       analysis2$sampleTable,
                                       design = as.formula( ~ Venetoclax))

analysis2$dds <- DESeq(analysis2$dds, parallel = TRUE)

```


```{r}
## Compare Any Venetoclax treatment (VA) to Only ART(A):(VA/A)
model_results <- list("VA/A" = results(analysis2$dds,
                         name = "Venetoclax_Venetoclax_vs_None",
                         alpha = 0.05,
                         filter = maxMinFilter(analysis2$dds,
                                               intgroup = "Venetoclax",
                                               comp = c("None","Venetoclax"))
                         ))

```


```{r}

analysis2$ddsGroup <- DESeqDataSetFromMatrix(counts(analysis2$dds),
                                            select(as.data.frame(colData(analysis2$dds)),
                                                   -c(sizeFactor,replaceable)),
                                            design = ~ Group)
analysis2$ddsGroup <- DESeq(analysis2$ddsGroup, parallel = TRUE)

```


```{r}
## Compare ART anti-CD8 Venetoclax (AVC) to ART Venetoclax (AV):(AVC/AV)
model_results$`AVC/AV` <- results(analysis2$ddsGroup,
                contrast = c("Group","ARTposVenetoclaxposantiposCD8","ARTposVenetoclax"),
                alpha = 0.05,
                filter = maxMinFilter(analysis2$ddsGroup,
                                      intgroup = "Group",
                                      comp = c("ARTposVenetoclaxposantiposCD8",
                                               "ARTposVenetoclax")))
```


```{r}
as.annot.data.frame(model_results[["VA/A"]],
                    subset = "All",
                    relabel = "Venetoclax Venetoclax vs None",
                    newlabel = "Venetoclax vs ART") %>%
  left_join(as.annot.data.frame(model_results[["AVC/AV"]],
                                subset = "All",
                                relabel = "Group ARTposVenetoclaxposantiposCD8 vs ARTposVenetoclax",
                                newlabel = "anti-CD8 Venetoclax vs Venetoclax")) %>%
  openxlsx::write.xlsx(file = "outputs/Merged_DESeq2_results_p24155_Tomas-manuscript.xlsx")
```


